include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - stations/**
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

formatter:
  trailing_commas: preserve

linter:
  rules:
    - require_trailing_commas
    - prefer_single_quotes
    - prefer_const_declarations
    - unnecessary_this
    - prefer_final_locals
    - omit_local_variable_types    